### ISSUE TITLE
Imgur for photos?

### ISSUE THREAD

**Issue by savvylee11** [mollykorroch/final-project#2]
Hi Molly! 

Maybe using Imgur for photos and hot linking them from there would help with the load time? I did something similar and that seemed to help for me! 

I would also maybe move some of the captions that were written over the photo to a more traditional caption, as to not take away from the photos. 

Loved everything else. Very clean from a design standpoint.

**Comment by mollykorroch** [comment]
Hey! Ok, so do you mean like forget the captions all the way and just do them underneath, or perhaps just add more of the black slides with the text on them? Thanks!

**Comment by savvylee11** [comment]
Just underneath!
